//ACTION WEBTOONS
export const GET_WEBTOONS = 'GET_WEBTOONS';
export const GET_FAVOURITES = 'GET_FAVOURITES';
export const GET_EPISODES = 'GET_EPISODES';
export const GET_IMAGES = 'GET_IMAGES';

//ACTION ACCOUNT
export const LOGIN = 'LOGIN';
export const GET_USER_WEBTOONS = 'GET_USER_WEBTOONS';
export const GET_USER_EPISODES = 'GET_USER_EPISODES';
export const DELETE_USER_EPISODE = 'DELETE_USER_EPISODE';
export const GET_USER_IMAGES = 'GET_USER_IMAGES';
